"""partial unique index for active booking slots

Revision ID: fe1d5b6b3537
Revises: aba443990203
Create Date: 2026-09-21 11:10:11.681429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1d5b6b3537'
down_revision: Union[str, Sequence[str], None] = 'aba443990203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_booking_court_date_start'), 'bookings', type_='unique')
    op.create_index('uq_booking_active_slot', 'bookings', ['court_id', 'date', 'start_time'], unique=True, postgresql_where=sa.text("status <> 'cancelled'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_booking_active_slot', table_name='bookings', postgresql_where=sa.text("status <> 'cancelled'"))
    op.create_unique_constraint(op.f('uq_booking_court_date_start'), 'bookings', ['court_id', 'date', 'start_time'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
